package com.bptn.feedapp.jpa;

import java.io.Serializable;
import java.sql.Timestamp;
import java.util.List;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonProperty.Access;

import jakarta.persistence.CascadeType;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.OneToOne;
import jakarta.persistence.Table;


@Entity // @Entity tells us this class will be our User table in our DB
@Table(name="\"User\"") // Tells us the name of the DB table
public class User implements Serializable { // Serializable is an interface that tells the compiler this class is serializable & can save,store,or send files 
	
	private static final long serialVersionUID = 1L; // Unique identifier used in the serialization & deserialization processes
	
	@Id // tells us that this is a PK
	@GeneratedValue(strategy=GenerationType.IDENTITY) // @GeneratedValue tells us that the value of the PK is Auto generated by the DB
                                                     // @GenerationType.IDENTITY Tells us the generated strategy here it is IDENTITY              
	@Column(name="\"userId\"") // @Column maps the annotated field to a column in the DB
	private Integer userId;
	
	@Column(name="\"firstName\"")
	private String firstName;
		
	@Column(name="\"lastName\"")
	private String lastName;

	private String username;

	@JsonProperty(access = Access.WRITE_ONLY)
	private String password;
		
	private String phone;

	@Column(name="\"emailId\"")
	private String emailId;
		
	@Column(name="\"emailVerified\"")
	private Boolean emailVerified;
		
	@Column(name="\"createdOn\"")
	private Timestamp createdOn;
	
	// Controls how null values are handled during JSON serialization
	// Include.NON_NULL  When passed to the JsonInclude() annotation, it specifies that properties with null values should be excluded from the JSON output
	// specifies a one-to-one relationship between user entity & profile entity
	@JsonInclude(Include.NON_NULL) 

	// cascade=CascadeType.ALL : Indicates that any change to the User entity will be cascaded down to the Profile entity.
	//fetch=FetchType.EAGER, Profile entity associated with the User should be fetched & the profile entity should be loaded immediately and completely.
	@OneToOne(mappedBy="user", cascade=CascadeType.ALL, fetch=FetchType.EAGER) 
	private Profile profile;

	
	@JsonIgnore // This annotation ignores the property during the serialization/deserialization
	@OneToMany(mappedBy="user") // Mapped by user field in feed entity
	private List<Feed> feeds;

	@JsonIgnore
	@OneToMany(mappedBy="user") // One-to-many relationship
	private List<FeedMetaData> feedMetaData;
	
	// constructor 
	public User() {
		
	}


	// GETTERS & SETTERS
	public Integer getUserId() {
		return userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public String getFirstName() {
		return firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getLastName() {
		return lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getUsername() {
		return username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getPhone() {
		return phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getEmailId() {
		return emailId;
	}

	public void setEmailId(String emailId) {
		this.emailId = emailId;
	}

	public Boolean getEmailVerified() {
		return emailVerified;
	}

	public void setEmailVerified(Boolean emailVerified) {
		this.emailVerified = emailVerified;
	}

	public Timestamp getCreatedOn() {
		return createdOn;
	}

	public void setCreatedOn(Timestamp createdOn) {
		this.createdOn = createdOn;
	}

	public Profile getProfile() {
		return profile;
	}

	public void setProfile(Profile profile) {
		this.profile = profile;
	}

	public List<Feed> getFeeds() {
		return feeds;
	}

	public void setFeeds(List<Feed> feeds) {
		this.feeds = feeds;
	}

	public List<FeedMetaData> getFeedMetaData() {
		return feedMetaData;
	}

	public void setFeedMetaData(List<FeedMetaData> feedMetaData) {
		this.feedMetaData = feedMetaData;
	}

	// toString Method
	@Override
	public String toString() {
		return "User [userId=" + userId + ", firstName=" + firstName + ", lastName=" + lastName + ", username="
				+ username + ", password=" + password + ", phone=" + phone + ", emailId=" + emailId + ", emailVerified="
				+ emailVerified + ", createdOn=" + createdOn + "]";
	}
	
	
	
}